yarnPath: .yarn/releases/yarn-2.4.0.cjs
packageExtensions:
  # Error: boxt tried to access chalk, but it isn't declared in its dependencies; this makes the require call ambiguous and unsound.
  'boxt@*':
    dependencies:
      chalk: '^4.0.0' # 5.x not working
